//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 10:10:04 PM CEST 
//


package com.holiday.agentApp.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Agent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Agent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.holiday.com/system}TUser">
 *       &lt;sequence>
 *         &lt;element name="PMB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.holiday.com/system}Location"/>
 *         &lt;element ref="{http://www.holiday.com/system}Accomodation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Agent", propOrder = {
	"id",
    "pmb",
    "location",
    "accomodation"
})
public class Agent
    extends TUser implements Serializable
{
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	protected Long id;
	
    @XmlElement(name = "PMB", required = true)
    protected String pmb;
    @XmlElement(name = "Location", required = true)
    @ManyToOne
    protected Location location;
    @XmlElement(name = "Accomodation")
    @OneToMany
    protected List<Accomodation> accomodation;

    /**
     * Gets the value of the pmb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Agent(){}
    public String getPMB() {
        return pmb;
    }

    /**
     * Sets the value of the pmb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPMB(String value) {
        this.pmb = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the accomodation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accomodation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccomodation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Accomodation }
     * 
     * 
     */
    public List<Accomodation> getAccomodation() {
        if (accomodation == null) {
            accomodation = new ArrayList<Accomodation>();
        }
        return this.accomodation;
    }

}
