//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.31 at 11:27:27 PM CEST 
//


package com.holiday.agentApp.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sender" type="{http://www.holiday.com/system}TUser"/>
 *         &lt;element name="receiver" type="{http://www.holiday.com/system}TUser"/>
 *         &lt;element ref="{http://www.holiday.com/inbox}Message" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"id",
    "sender",
    "receiver",
    "message"
})
@XmlRootElement(name = "Inbox", namespace = "http://www.holiday.com/inbox")
@Entity(name="Inbox")
public class Inbox {

	public Long getId() {
		return id;
	}

	public void setMessage(List<Message> message) {
		this.message = message;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	protected Long id;
	
    @XmlElement(namespace = "http://www.holiday.com/inbox", required = true)
    @ManyToOne
    protected TUser sender;
    @XmlElement(namespace = "http://www.holiday.com/inbox", required = true)
    @ManyToOne
    protected TUser receiver;
    @XmlElement(name = "Message", namespace = "http://www.holiday.com/inbox", required = true)
    @OneToMany
    protected List<Message> message;

    
    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link TUser }
     *     
     */
    public TUser getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUser }
     *     
     */
    public void setSender(TUser value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link TUser }
     *     
     */
    public TUser getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUser }
     *     
     */
    public void setReceiver(TUser value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     */
    public List<Message> getMessage() {
        if (message == null) {
            message = new ArrayList<Message>();
        }
        return this.message;
    }

}
