
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.holiday.agentApp.webService;
import javax.jws.WebService;

import org.springframework.beans.factory.annotation.Autowired;

import com.holiday.agentApp.repository.AccomodationRepository;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2018-05-28T22:44:12.649+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(endpointInterface = "com.holiday.agentApp.webService.AccomodationWebService", serviceName = "AccomodationWebService")                      
public class AccomodationWebServiceImpl implements AccomodationWebService {

	private AccomodationRepository accomodatioRepository;

	@Autowired
	public AccomodationWebServiceImpl(AccomodationRepository accomodatioRepository) {
		this.accomodatioRepository = accomodatioRepository;
	}
    public com.holiday.agentApp.model.Accomodation findById(java.lang.Long arg0) {  
        System.out.println(arg0);    
        try {
            com.holiday.agentApp.model.Accomodation _return =accomodatioRepository.findOne(arg0);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
 
    }

}