
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.holiday.agentApp.webService;
import java.sql.DriverManager;
import java.sql.SQLException;

import javax.jws.WebService;

import com.holiday.agentApp.model.Agent;
import com.holiday.agentApp.model.Location;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2018-05-29T12:03:10.938+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(endpointInterface = "com.holiday.agentApp.webService.SyncService", serviceName = "SyncService")                      
public class SyncServiceImpl implements SyncService {

    public void sync(com.holiday.agentApp.model.Accomodation arg0) {  
        System.out.println(arg0);    
        Agent a=new Agent();
        a.setId(1L);
        arg0.setOwner(a);
        try {
			Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/xml?useSSL=false&createDatabaseIfNotExist=true","root","malizvornik95");
			PreparedStatement statement=(PreparedStatement) connection.prepareStatement("insert into accomodation (description,max_person,name,category_id,location_id,price_shedule_id,type_id)  values  (?,?, ?, ?, ?, ?, ?)");
			statement.setString(1, arg0.getDescription());
			statement.setInt(2, arg0.getMaxPerson());
			statement.setString(3, arg0.getName());
			statement.setLong(4, arg0.getCategory().getId());
			statement.setLong(5, arg0.getLocation().getId());
			
			
			statement.setLong(6, arg0.getPriceShedule().getId());
			statement.setLong(7, arg0.getType().getId());
			System.out.println(statement.toString());
			
			statement.execute();
			connection.close();
        } catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
    }

}