//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 03:04:43 PM CEST 
//

package com.holiday.agentApp.requestAndResponse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.holiday.agentApp.model.Accomodation;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Id_QNAME = new QName("http://www.holiday.com/system", "id");
    private final static QName _LocationRequest_QNAME = new QName("http://webService.projekat.xml/", "locationRequest");
    private final static QName _LocationResponse_QNAME = new QName("http://webService.projekat.xml/", "locationResponse");
    private final static QName _LocationByIdRequest_QNAME = new QName("http://webService.projekat.xml/", "locationByIdRequest");
    private final static QName _LocationByIdResponse_QNAME = new QName("http://webService.projekat.xml/", "locationByIdResponse");
    private final static QName _MessageSaveRequest_QNAME = new QName("http://webService.projekat.xml/", "messageSaveRequest");
    private final static QName _MessageSaveResponse_QNAME = new QName("http://webService.projekat.xml/", "messageSaveResponse");
    private final static QName _MessagesAllRequest_QNAME = new QName("http://webService.projekat.xml/", "messagesAllRequest");
    private final static QName _MessagesAllResponse_QNAME = new QName("http://webService.projekat.xml/", "messagesAllResponse");
    private final static QName _InboxAllRequest_QNAME = new QName("http://webService.projekat.xml/", "inboxAllRequest");
    private final static QName _InboxAllResponse_QNAME = new QName("http://webService.projekat.xml/", "inboxAllResponse");
    private final static QName _InboxByIdRequest_QNAME = new QName("http://webService.projekat.xml/", "inboxByIdRequest");
    private final static QName _InboxByIdResponse_QNAME = new QName("http://webService.projekat.xml/", "inboxByIdResponse");
    private final static QName _InboxReceiverRequest_QNAME = new QName("http://webService.projekat.xml/", "inboxReceiverRequest");
    private final static QName _InboxReceiverResponse_QNAME = new QName("http://webService.projekat.xml/", "inboxReceiverResponse");
    private final static QName _MessageByInboxRequest_QNAME = new QName("http://webService.projekat.xml/", "messageByInboxRequest");
    private final static QName _MessageByInboxResponse_QNAME = new QName("http://webService.projekat.xml/", "messageByInboxResponse");
    private final static QName _UserByIdRequest_QNAME = new QName("http://webService.projekat.xml/", "userByIdRequest");
    private final static QName _UserByIdResponse_QNAME = new QName("http://webService.projekat.xml/", "userByIdResponse");
    private final static QName _ArrangmentAllRequest_QNAME = new QName("http://webService.projekat.xml/", "arrangmentAllRequest");
    private final static QName _ArrangmentAllResponse_QNAME = new QName("http://webService.projekat.xml/", "arrangmentAllResponse");
    private final static QName _ArrangmentUpdateRequest_QNAME = new QName("http://webService.projekat.xml/", "arrangmentUpdateRequest");
    private final static QName _ArrangmentUpdateResponse_QNAME = new QName("http://webService.projekat.xml/", "arrangmentUpdateResponse");
    private final static QName _AccomodationSaveRequest_QNAME = new QName("http://webService.projekat.xml/", "accomodationSaveRequest");
    private final static QName _AccomodationSaveResponse_QNAME = new QName("http://webService.projekat.xml/", "accomodationSaveResponse");
    
    private final static QName _ServiceAllRequest_QNAME = new QName("http://webService.projekat.xml/", "serviceAllRequest");
    private final static QName _ServiceAllResponse_QNAME = new QName("http://webService.projekat.xml/", "serviceAllResponse");
    private final static QName _ServiceByIdRequest_QNAME = new QName("http://webService.projekat.xml/", "serviceByIdRequest");
    private final static QName _ServiceByIdResponse_QNAME = new QName("http://webService.projekat.xml/", "serviceByIdResponse");

    private final static QName _ObjectCategoryAllRequest_QNAME = new QName("http://webService.projekat.xml/", "objectCategoryAllRequest");
    private final static QName _ObjectCategoryAllResponse_QNAME = new QName("http://webService.projekat.xml/", "objectCategoryAllResponse");
    private final static QName _ObjectCategoryByIdRequest_QNAME = new QName("http://webService.projekat.xml/", "objectCategoryByIdRequest");
    private final static QName _ObjectCategoryByIdResponse_QNAME = new QName("http://webService.projekat.xml/", "objectCategoryByIdResponse");

    private final static QName _ObjectTypeAllRequest_QNAME = new QName("http://webService.projekat.xml/", "objectTypeAllRequest");
    private final static QName _ObjectTypeAllResponse_QNAME = new QName("http://webService.projekat.xml/", "objectTypeAllResponse");
    private final static QName _ObjectTypeByIdRequest_QNAME = new QName("http://webService.projekat.xml/", "objectTypeByIdRequest");
    private final static QName _ObjectTypeByIdResponse_QNAME = new QName("http://webService.projekat.xml/", "objectTypeByIdResponse");

    private final static QName _LocationSaveRequest_QNAME = new QName("http://webService.projekat.xml/", "locationSaveRequest");
    private final static QName _LocationSaveResponse_QNAME = new QName("http://webService.projekat.xml/", "locationSaveResponse");

    private final static QName _AccomodationFindRequest_QNAME = new QName("http://webService.projekat.xml/", "accomodationFindRequest");
    private final static QName _AccomodationFindResponse_QNAME = new QName("http://webService.projekat.xml/", "accomodationFindResponse");
  
    private final static QName _ArrangmentFindRequest_QNAME = new QName("http://webService.projekat.xml/", "arrangmentFindRequest");
    private final static QName _ArrangmentFindResponse_QNAME = new QName("http://webService.projekat.xml/", "arrangmentFindResponse");
    private final static QName _ArrangmentSaveRequest_QNAME = new QName("http://webService.projekat.xml/", "arrangmentSaveRequest");
    private final static QName _ArrangmentSaveResponse_QNAME = new QName("http://webService.projekat.xml/", "arrangmentSaveResponse");
   
    private final static QName _AccomodationFindByOwnerRequest_QNAME = new QName("http://webService.projekat.xml/", "accomodationFindByOwnerRequest");
    private final static QName _AccomodationFindByOwnerResponse_QNAME = new QName("http://webService.projekat.xml/", "accomodationFindByOwnerResponse");
    
    private final static QName _ArrangmentFindByAccOwnerRequest_QNAME = new QName("http://webService.projekat.xml/", "arrangmentFindByAccOwnerRequest");
    private final static QName _ArrangmentFindByAccOwnerResponse_QNAME = new QName("http://webService.projekat.xml/", "arrangmentFindByAccOwnerResponse");
   
    private final static QName _AccomodationDeleteRequest_QNAME = new QName("http://webService.projekat.xml/", "accomodationDeleteRequest");
    
    private final static QName _RatingFindByIdRequest_QNAME = new QName("http://webService.projekat.xml/", "RatingFindByIdRequest");
    private final static QName _RatingFindByIdResponse_QNAME = new QName("http://webService.projekat.xml/", "RatingFindByIdResponse");

    private final static QName _RatingSaveRequest_QNAME = new QName("http://webService.projekat.xml/", "ratingSaveRequest");
    private final static QName _RatingSaveResponse_QNAME = new QName("http://webService.projekat.xml/", "ratingSaveResponse");

    private final static QName _PriceSaveRequest_QNAME = new QName("http://webService.projekat.xml/", "priceSaveRequest");
    private final static QName _PriceSaveResponse_QNAME = new QName("http://webService.projekat.xml/", "priceSaveResponse");

    private final static QName _PriceSheduleSaveRequest_QNAME = new QName("http://webService.projekat.xml/", "priceSheduleSaveRequest");
    private final static QName _PriceSheduleSaveResponse_QNAME = new QName("http://webService.projekat.xml/", "priceSheduleSaveResponse");
    private final static QName _DeleteResponse_QNAME = new QName("http://webService.projekat.xml/", "deleteResponse");

    private final static QName _UserFindByEmailAndPasswordRequest_QNAME = new QName("http://webService.projekat.xml/", "userFindByEmailAndPasswordRequest");
    private final static QName _UserFindByEmailAndPasswordResponse_QNAME = new QName("http://webService.projekat.xml/", "userFindByEmailAndPasswordResponse");

    private final static QName _RatingFindByAccRequest_QNAME = new QName("http://webService.projekat.xml/", "ratingFindByAccRequest");
    private final static QName _RatingFindByAccResponse_QNAME = new QName("http://webService.projekat.xml/", "ratingFindByAccResponse");
  
    private final static QName _CommentFindByAccRequest_QNAME = new QName("http://webService.projekat.xml/", "commentFindByAccRequest");
    private final static QName _CommentFindByAccResponse_QNAME = new QName("http://webService.projekat.xml/", "commentFindByAccResponse");

    private final static QName _MessageUpdateRequest_QNAME = new QName("http://webService.projekat.xml/", "messageUpdateRequest");
    private final static QName _MessageUpdateResponse_QNAME = new QName("http://webService.projekat.xml/", "messageUpdateResponse");
    
    /**
     * Create an instance of {@link CommentFindByAccResponse }
     * 
     */
    public CommentFindByAccResponse createCommentFindByAccResponse() {
        return new CommentFindByAccResponse();
    }

    /**
     * Create an instance of {@link CommentFindByAccRequest }
     * 
     */
    public CommentFindByAccRequest createCommentFindByAccRequest() {
        return new CommentFindByAccRequest();
    }
    /**
     * Create an instance of {@link AccomodationFindResponse }
     * 
     */
    public AccomodationFindResponse createAccomodationFindResponse() {
        return new AccomodationFindResponse();
    }
    
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.wsdl
     * 
     */
    public ObjectFactory() {
    }
    /**
     * Create an instance of {@link ObjectCategoryAllResponse }
     * 
     */
    public ObjectCategoryAllResponse createObjectCategoryAllResponse() {
        return new ObjectCategoryAllResponse();
    }
    /**
     * Create an instance of {@link ObjectTypeAllResponse }
     * 
     */
    public ObjectTypeAllResponse createObjectTypeAllResponse() {
        return new ObjectTypeAllResponse();
    }
    /**
     * Create an instance of {@link ObjectTypeAllRequest }
     * 
     */
    public ObjectTypeAllRequest createObjectTypeAllRequest() {
        return new ObjectTypeAllRequest();
    }
    /**
     * Create an instance of {@link RatingFindByIdRequest }
     * 
     */
    public RatingFindByIdRequest createRatingFindByIdRequest() {
        return new RatingFindByIdRequest();
    }
    /**
     * Create an instance of {@link RatingSaveResponse }
     * 
     */
    public RatingSaveResponse createRatingSaveResponse() {
        return new RatingSaveResponse();
    }

    /**
     * Create an instance of {@link RatingSaveRequest }
     * 
     */
    public RatingSaveRequest createRatingSaveRequest() {
        return new RatingSaveRequest();
    }
    /**
     * Create an instance of {@link RatingFindByIdResponse }
     * 
     */
    public RatingFindByIdResponse createRatingFindByIdResponse() {
        return new RatingFindByIdResponse();
    }
    /**
     * Create an instance of {@link LocationSaveResponse }
     * 
     */
    public LocationSaveResponse createLocationSaveResponse() {
        return new LocationSaveResponse();
    }

    /**
     * Create an instance of {@link LocationSaveRequest }
     * 
     */
    public LocationSaveRequest createLocationSaveRequest() {
        return new LocationSaveRequest();
    }

    /**
     * Create an instance of {@link DeleteResponse }
     * 
     */
    public DeleteResponse createDeleteResponse() {
        return new DeleteResponse();
    }
    /**
     * Create an instance of {@link UserFindByEmailAndPasswordRequest }
     * 
     */
    public UserFindByEmailAndPasswordRequest createUserFindByEmailAndPasswordRequest() {
        return new UserFindByEmailAndPasswordRequest();
    }

    /**
     * Create an instance of {@link UserFindByEmailAndPasswordResponse }
     * 
     */
    public UserFindByEmailAndPasswordResponse createUserFindByEmailAndPasswordResponse() {
        return new UserFindByEmailAndPasswordResponse();
    }
    /**
     * Create an instance of {@link ObjectCategoryByIdResponse }
     * 
     */
    public ObjectCategoryByIdResponse createObjectCategoryByIdResponse() {
        return new ObjectCategoryByIdResponse();
    }

    /**
     * Create an instance of {@link ObjectCategoryByIdRequest }
     * 
     */
    public ObjectCategoryByIdRequest createObjectCategoryByIdRequest() {
        return new ObjectCategoryByIdRequest();
    }
    /**
     * Create an instance of {@link ArrangmentUpdateResponse }
     * 
     */
    public ArrangmentUpdateResponse createArrangmentUpdateResponse() {
        return new ArrangmentUpdateResponse();
    }
    /**
     * Create an instance of {@link RatingFindByAccResponse }
     * 
     */
    public RatingFindByAccResponse createRatingFindByAccResponse() {
        return new RatingFindByAccResponse();
    }

    /**
     * Create an instance of {@link RatingFindByAccRequest }
     * 
     */
    public RatingFindByAccRequest createRatingFindByAccRequest() {
        return new RatingFindByAccRequest();
    }
    /**
     * Create an instance of {@link ObjectCategoryAllRequest }
     * 
     */
    public ObjectCategoryAllRequest createObjectCategoryAllRequest() {
        return new ObjectCategoryAllRequest();
    }
    /**
     * Create an instance of {@link ArrangmentAllResponse }
     * 
     */
    public ArrangmentAllResponse createArrangmentAllResponse() {
        return new ArrangmentAllResponse();
    }
    public LocationResponse createLocationResponse() {
        return new LocationResponse();
    }
    


    /**
     * Create an instance of {@link ServiceByIdResponse }
     * 
     */
    public ServiceByIdResponse createServiceByIdResponse() {
        return new ServiceByIdResponse();
    }

    /**
     * Create an instance of {@link ServiceAllResponse }
     * 
     */
    public ServiceAllResponse createServiceAllResponse() {
        return new ServiceAllResponse();
    }
    /**
     * Create an instance of {@link ServiceAllRequest }
     * 
     */
    public ServiceAllRequest createServiceAllRequest() {
        return new ServiceAllRequest();
    }

    /**
     * Create an instance of {@link ServiceByIdRequest }
     * 
     */
    public ServiceByIdRequest createServiceByIdRequest() {
        return new ServiceByIdRequest();
    }

    /**
     * Create an instance of {@link ArrangmentAllRequest }
     * 
     */
    public ArrangmentAllRequest createArrangmentAllRequest() {
        return new ArrangmentAllRequest();
    }

    /**
     * Create an instance of {@link ArrangmentUpdateRequest }
     * 
     */
    public ArrangmentUpdateRequest createArrangmentUpdateRequest() {
        return new ArrangmentUpdateRequest();
    }
    /**
     * Create an instance of {@link MessageByInboxResponse }
     * 
     */
    public MessageByInboxResponse createMessageByInboxResponse() {
        return new MessageByInboxResponse();
    }
    /**
     * Create an instance of {@link MessageByInboxRequest }
     * 
     */
    public MessageByInboxRequest createMessageByInboxRequest() {
        return new MessageByInboxRequest();
    }
    public InboxReceiverResponse createInboxReceiverResponse() {
        return new InboxReceiverResponse();
    }
    /**
     * Create an instance of {@link InboxAllResponse }
     * 
     */
    public InboxAllResponse createInboxAllResponse() {
        return new InboxAllResponse();
    }
    /**
     * Create an instance of {@link InboxAllRequest }
     * 
     */
    public InboxAllRequest createInboxAllRequest() {
        return new InboxAllRequest();
    }

    /**
     * Create an instance of {@link InboxByIdRequest }
     * 
     */
    public InboxByIdRequest createInboxByIdRequest() {
        return new InboxByIdRequest();
    }
    
    /**
     * Create an instance of {@link InboxReceiverRequest }
     * 
     */
    public InboxReceiverRequest createInboxReceiverRequest() {
        return new InboxReceiverRequest();
    }
    /**
     * Create an instance of {@link PriceSaveResponse }
     * 
     */
    public PriceSaveResponse createPriceSaveResponse() {
        return new PriceSaveResponse();
    }

    /**
     * Create an instance of {@link PriceSaveRequest }
     * 
     */
    public PriceSaveRequest createPriceSaveRequest() {
        return new PriceSaveRequest();
    }

    /**
     * Create an instance of {@link InboxByIdResponse }
     * 
     */
    public InboxByIdResponse createInboxByIdResponse() {
        return new InboxByIdResponse();
    }
   
    /**
     * Create an instance of {@link MessagesAllResponse }
     * 
     */
    public MessagesAllResponse createMessagesAllResponse() {
        return new MessagesAllResponse();
    }

    /**
     * Create an instance of {@link MessageSaveResponse }
     * 
     */
    public MessageSaveResponse createMessageSaveResponse() {
        return new MessageSaveResponse();
    }
    /**
     * Create an instance of {@link MessageSaveRequest }
     * 
     */
    public MessageSaveRequest createMessageSaveRequest() {
        return new MessageSaveRequest();
    }
    /**
     * Create an instance of {@link LocationRequest }
     * 
     */
    public LocationRequest createLocationRequest() {
        return new LocationRequest();
    }
    /**
     * Create an instance of {@link AccomodationDeleteRequest }
     * 
     */
    public AccomodationDeleteRequest createAccomodationDeleteRequest() {
        return new AccomodationDeleteRequest();
    }
    /**
     * Create an instance of {@link LocationByIdResponse }
     *
     */
    public LocationByIdResponse createLocationByIdResponse() {
        return new LocationByIdResponse();
    }
    /**
     * Create an instance of {@link AccomodationSaveRequest }
     * 
     */
    public AccomodationSaveRequest createAccomodationSaveRequest() {
        return new AccomodationSaveRequest();
    }
    /**
     * Create an instance of {@link ObjectTypeByIdRequest }
     * 
     */
    public ObjectTypeByIdRequest createObjectTypeByIdRequest() {
        return new ObjectTypeByIdRequest();
    }
    /**
     * Create an instance of {@link ObjectTypeByIdResponse }
     * 
     */
    public ObjectTypeByIdResponse createObjectTypeByIdResponse() {
        return new ObjectTypeByIdResponse();
    }
    /**
     * Create an instance of {@link LocationByIdRequest }
     *
     */
    public LocationByIdRequest createLocationByIdRequest() {
        return new LocationByIdRequest();
    }
    /**
     * Create an instance of {@link AccomodationSaveResponse }
     * 
     */
    public AccomodationSaveResponse createAccomodationSaveResponse() {
        return new AccomodationSaveResponse();
    }
    /**
     * Create an instance of {@link MessagesAllRequest }
     * 
     */
    public MessagesAllRequest createMessagesAllRequest() {
        return new MessagesAllRequest();
    }
    /**
     * Create an instance of {@link PriceSheduleSaveResponse }
     * 
     */
    public PriceSheduleSaveResponse createPriceSheduleSaveResponse() {
        return new PriceSheduleSaveResponse();
    }
    /**
     * Create an instance of {@link MessageUpdateRequest }
     * 
     */
    public MessageUpdateRequest createMessageUpdateRequest() {
        return new MessageUpdateRequest();
    }

    /**
     * Create an instance of {@link MessageUpdateResponse }
     * 
     */
    public MessageUpdateResponse createMessageUpdateResponse() {
        return new MessageUpdateResponse();
    }

    /**
     * Create an instance of {@link PriceSheduleSaveRequest }
     * 
     */
    public PriceSheduleSaveRequest createPriceSheduleSaveRequest() {
        return new PriceSheduleSaveRequest();
    }
    /**
     * Create an instance of {@link UserByIdRequest }
     * 
     */
    public UserByIdRequest createUserByIdRequest() {
        return new UserByIdRequest();
    }
    /**
     * Create an instance of {@link AccomodationFindByOwnerRequest }
     * 
     */
    public AccomodationFindByOwnerRequest createAccomodationFindByOwnerRequest() {
        return new AccomodationFindByOwnerRequest();
    }
    /**
     * Create an instance of {@link AccomodationFindByOwnerResponse }
     * 
     */
    public AccomodationFindByOwnerResponse createAccomodationFindByOwnerResponse() {
        return new AccomodationFindByOwnerResponse();
    }
    /**
     * Create an instance of {@link UserByIdResponse }
     * 
     */
    public UserByIdResponse createUserByIdResponse() {
        return new UserByIdResponse();
    }
    /**
     * Create an instance of {@link ArrangmentSaveResponse }
     * 
     */
    public ArrangmentSaveResponse createArrangmentSaveResponse() {
        return new ArrangmentSaveResponse();
    }

    /**
     * Create an instance of {@link ArrangmentSaveRequest }
     * 
     */
    public ArrangmentSaveRequest createArrangmentSaveRequest() {
        return new ArrangmentSaveRequest();
    }
    /**
     * Create an instance of {@link ArrangmentFindResponse }
     * 
     */
    public ArrangmentFindResponse createArrangmentFindResponse() {
        return new ArrangmentFindResponse();
    }

    /**
     * Create an instance of {@link ArrangmentFindRequest }
     * 
     */
    public ArrangmentFindRequest createArrangmentFindRequest() {
        return new ArrangmentFindRequest();
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.holiday.com/system", name = "id")
    public JAXBElement<Long> createId(Long value) {
        return new JAXBElement<Long>(_Id_QNAME, Long.class, null, value);
    }
    /**
     * Create an instance of {@link ArrangmentFindByAccOwnerRequest }
     * 
     */
    public ArrangmentFindByAccOwnerRequest createArrangmentFindByAccOwnerRequest() {
        return new ArrangmentFindByAccOwnerRequest();
    }
    /**
     * Create an instance of {@link ArrangmentFindByAccOwnerResponse }
     * 
     */
    public ArrangmentFindByAccOwnerResponse createArrangmentFindByAccOwnerResponse() {
        return new ArrangmentFindByAccOwnerResponse();
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "locationRequest")
    public JAXBElement<LocationRequest> createLocationRequest(LocationRequest value) {
        return new JAXBElement<LocationRequest>(_LocationRequest_QNAME, LocationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "locationResponse")
    public JAXBElement<LocationResponse> createLocationResponse(LocationResponse value) {
        return new JAXBElement<LocationResponse>(_LocationResponse_QNAME, LocationResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationByIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "locationByIdRequest")
    public JAXBElement<LocationByIdRequest> createLocationByIdRequest(LocationByIdRequest value) {
        return new JAXBElement<LocationByIdRequest>(_LocationByIdRequest_QNAME, LocationByIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "locationByIdResponse")
    public JAXBElement<LocationByIdResponse> createLocationByIdResponse(LocationByIdResponse value) {
        return new JAXBElement<LocationByIdResponse>(_LocationByIdResponse_QNAME, LocationByIdResponse.class, null, value);
    }
   
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageSaveRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "messageSaveRequest")
    public JAXBElement<MessageSaveRequest> createMessageSaveRequest(MessageSaveRequest value) {
        return new JAXBElement<MessageSaveRequest>(_MessageSaveRequest_QNAME, MessageSaveRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageSaveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "messageSaveResponse")
    public JAXBElement<MessageSaveResponse> createMessageSaveResponse(MessageSaveResponse value) {
        return new JAXBElement<MessageSaveResponse>(_MessageSaveResponse_QNAME, MessageSaveResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessagesAllRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "messagesAllRequest")
    public JAXBElement<MessagesAllRequest> createMessagesAllRequest(MessagesAllRequest value) {
        return new JAXBElement<MessagesAllRequest>(_MessagesAllRequest_QNAME, MessagesAllRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessagesAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "messagesAllResponse")
    public JAXBElement<MessagesAllResponse> createMessagesAllResponse(MessagesAllResponse value) {
        return new JAXBElement<MessagesAllResponse>(_MessagesAllResponse_QNAME, MessagesAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InboxAllRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "inboxAllRequest")
    public JAXBElement<InboxAllRequest> createInboxAllRequest(InboxAllRequest value) {
        return new JAXBElement<InboxAllRequest>(_InboxAllRequest_QNAME, InboxAllRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InboxAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "inboxAllResponse")
    public JAXBElement<InboxAllResponse> createInboxAllResponse(InboxAllResponse value) {
        return new JAXBElement<InboxAllResponse>(_InboxAllResponse_QNAME, InboxAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InboxByIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "inboxByIdRequest")
    public JAXBElement<InboxByIdRequest> createInboxByIdRequest(InboxByIdRequest value) {
        return new JAXBElement<InboxByIdRequest>(_InboxByIdRequest_QNAME, InboxByIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InboxByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "inboxByIdResponse")
    public JAXBElement<InboxByIdResponse> createInboxByIdResponse(InboxByIdResponse value) {
        return new JAXBElement<InboxByIdResponse>(_InboxByIdResponse_QNAME, InboxByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InboxReceiverRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "inboxReceiverRequest")
    public JAXBElement<InboxReceiverRequest> createInboxReceiverRequest(InboxReceiverRequest value) {
        return new JAXBElement<InboxReceiverRequest>(_InboxReceiverRequest_QNAME, InboxReceiverRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InboxReceiverResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "inboxReceiverResponse")
    public JAXBElement<InboxReceiverResponse> createInboxReceiverResponse(InboxReceiverResponse value) {
        return new JAXBElement<InboxReceiverResponse>(_InboxReceiverResponse_QNAME, InboxReceiverResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageByInboxRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "messageByInboxRequest")
    public JAXBElement<MessageByInboxRequest> createMessageByInboxRequest(MessageByInboxRequest value) {
        return new JAXBElement<MessageByInboxRequest>(_MessageByInboxRequest_QNAME, MessageByInboxRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageByInboxResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "messageByInboxResponse")
    public JAXBElement<MessageByInboxResponse> createMessageByInboxResponse(MessageByInboxResponse value) {
        return new JAXBElement<MessageByInboxResponse>(_MessageByInboxResponse_QNAME, MessageByInboxResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserByIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "userByIdRequest")
    public JAXBElement<UserByIdRequest> createUserByIdRequest(UserByIdRequest value) {
        return new JAXBElement<UserByIdRequest>(_UserByIdRequest_QNAME, UserByIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "userByIdResponse")
    public JAXBElement<UserByIdResponse> createUserByIdResponse(UserByIdResponse value) {
        return new JAXBElement<UserByIdResponse>(_UserByIdResponse_QNAME, UserByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentAllRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentAllRequest")
    public JAXBElement<ArrangmentAllRequest> createArrangmentAllRequest(ArrangmentAllRequest value) {
        return new JAXBElement<ArrangmentAllRequest>(_ArrangmentAllRequest_QNAME, ArrangmentAllRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentAllResponse")
    public JAXBElement<ArrangmentAllResponse> createArrangmentAllResponse(ArrangmentAllResponse value) {
        return new JAXBElement<ArrangmentAllResponse>(_ArrangmentAllResponse_QNAME, ArrangmentAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentUpdateRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentUpdateRequest")
    public JAXBElement<ArrangmentUpdateRequest> createArrangmentUpdateRequest(ArrangmentUpdateRequest value) {
        return new JAXBElement<ArrangmentUpdateRequest>(_ArrangmentUpdateRequest_QNAME, ArrangmentUpdateRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentUpdateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentUpdateResponse")
    public JAXBElement<ArrangmentUpdateResponse> createArrangmentUpdateResponse(ArrangmentUpdateResponse value) {
        return new JAXBElement<ArrangmentUpdateResponse>(_ArrangmentUpdateResponse_QNAME, ArrangmentUpdateResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccomodationSaveRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "accomodationSaveRequest")
    public JAXBElement<AccomodationSaveRequest> createAccomodationSaveRequest(AccomodationSaveRequest value) {
        return new JAXBElement<AccomodationSaveRequest>(_AccomodationSaveRequest_QNAME, AccomodationSaveRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccomodationSaveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "accomodationSaveResponse")
    public JAXBElement<AccomodationSaveResponse> createAccomodationSaveResponse(AccomodationSaveResponse value) {
        return new JAXBElement<AccomodationSaveResponse>(_AccomodationSaveResponse_QNAME, AccomodationSaveResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceAllRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "serviceAllRequest")
    public JAXBElement<ServiceAllRequest> createServiceAllRequest(ServiceAllRequest value) {
        return new JAXBElement<ServiceAllRequest>(_ServiceAllRequest_QNAME, ServiceAllRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "serviceAllResponse")
    public JAXBElement<ServiceAllResponse> createServiceAllResponse(ServiceAllResponse value) {
        return new JAXBElement<ServiceAllResponse>(_ServiceAllResponse_QNAME, ServiceAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceByIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "serviceByIdRequest")
    public JAXBElement<ServiceByIdRequest> createServiceByIdRequest(ServiceByIdRequest value) {
        return new JAXBElement<ServiceByIdRequest>(_ServiceByIdRequest_QNAME, ServiceByIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "serviceByIdResponse")
    public JAXBElement<ServiceByIdResponse> createServiceByIdResponse(ServiceByIdResponse value) {
        return new JAXBElement<ServiceByIdResponse>(_ServiceByIdResponse_QNAME, ServiceByIdResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectCategoryAllRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "objectCategoryAllRequest")
    public JAXBElement<ObjectCategoryAllRequest> createObjectCategoryAllRequest(ObjectCategoryAllRequest value) {
        return new JAXBElement<ObjectCategoryAllRequest>(_ObjectCategoryAllRequest_QNAME, ObjectCategoryAllRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectCategoryAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "objectCategoryAllResponse")
    public JAXBElement<ObjectCategoryAllResponse> createObjectCategoryAllResponse(ObjectCategoryAllResponse value) {
        return new JAXBElement<ObjectCategoryAllResponse>(_ObjectCategoryAllResponse_QNAME, ObjectCategoryAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectTypeAllRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "objectTypeAllRequest")
    public JAXBElement<ObjectTypeAllRequest> createObjectTypeAllRequest(ObjectTypeAllRequest value) {
        return new JAXBElement<ObjectTypeAllRequest>(_ObjectTypeAllRequest_QNAME, ObjectTypeAllRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectTypeAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "objectTypeAllResponse")
    public JAXBElement<ObjectTypeAllResponse> createObjectTypeAllResponse(ObjectTypeAllResponse value) {
        return new JAXBElement<ObjectTypeAllResponse>(_ObjectTypeAllResponse_QNAME, ObjectTypeAllResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectTypeByIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "objectTypeByIdRequest")
    public JAXBElement<ObjectTypeByIdRequest> createObjectTypeByIdRequest(ObjectTypeByIdRequest value) {
        return new JAXBElement<ObjectTypeByIdRequest>(_ObjectTypeByIdRequest_QNAME, ObjectTypeByIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectTypeByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "objectTypeByIdResponse")
    public JAXBElement<ObjectTypeByIdResponse> createObjectTypeByIdResponse(ObjectTypeByIdResponse value) {
        return new JAXBElement<ObjectTypeByIdResponse>(_ObjectTypeByIdResponse_QNAME, ObjectTypeByIdResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectCategoryByIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "objectCategoryByIdRequest")
    public JAXBElement<ObjectCategoryByIdRequest> createObjectCategoryByIdRequest(ObjectCategoryByIdRequest value) {
        return new JAXBElement<ObjectCategoryByIdRequest>(_ObjectCategoryByIdRequest_QNAME, ObjectCategoryByIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectCategoryByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "objectCategoryByIdResponse")
    public JAXBElement<ObjectCategoryByIdResponse> createObjectCategoryByIdResponse(ObjectCategoryByIdResponse value) {
        return new JAXBElement<ObjectCategoryByIdResponse>(_ObjectCategoryByIdResponse_QNAME, ObjectCategoryByIdResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationSaveRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "locationSaveRequest")
    public JAXBElement<LocationSaveRequest> createLocationSaveRequest(LocationSaveRequest value) {
        return new JAXBElement<LocationSaveRequest>(_LocationSaveRequest_QNAME, LocationSaveRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationSaveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "locationSaveResponse")
    public JAXBElement<LocationSaveResponse> createLocationSaveResponse(LocationSaveResponse value) {
        return new JAXBElement<LocationSaveResponse>(_LocationSaveResponse_QNAME, LocationSaveResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccomodationFindRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "accomodationFindRequest")
    public JAXBElement<AccomodationFindRequest> createAccomodationFindRequest(AccomodationFindRequest value) {
        return new JAXBElement<AccomodationFindRequest>(_AccomodationFindRequest_QNAME, AccomodationFindRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccomodationFindResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "accomodationFindResponse")
    public JAXBElement<AccomodationFindResponse> createAccomodationFindResponse(AccomodationFindResponse value) {
        return new JAXBElement<AccomodationFindResponse>(_AccomodationFindResponse_QNAME, AccomodationFindResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentFindRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentFindRequest")
    public JAXBElement<ArrangmentFindRequest> createArrangmentFindRequest(ArrangmentFindRequest value) {
        return new JAXBElement<ArrangmentFindRequest>(_ArrangmentFindRequest_QNAME, ArrangmentFindRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentFindResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentFindResponse")
    public JAXBElement<ArrangmentFindResponse> createArrangmentFindResponse(ArrangmentFindResponse value) {
        return new JAXBElement<ArrangmentFindResponse>(_ArrangmentFindResponse_QNAME, ArrangmentFindResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentSaveRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentSaveRequest")
    public JAXBElement<ArrangmentSaveRequest> createArrangmentSaveRequest(ArrangmentSaveRequest value) {
        return new JAXBElement<ArrangmentSaveRequest>(_ArrangmentSaveRequest_QNAME, ArrangmentSaveRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentSaveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentSaveResponse")
    public JAXBElement<ArrangmentSaveResponse> createArrangmentSaveResponse(ArrangmentSaveResponse value) {
        return new JAXBElement<ArrangmentSaveResponse>(_ArrangmentSaveResponse_QNAME, ArrangmentSaveResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccomodationFindByOwnerRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "accomodationFindByOwnerRequest")
    public JAXBElement<AccomodationFindByOwnerRequest> createAccomodationFindByOwnerRequest(AccomodationFindByOwnerRequest value) {
        return new JAXBElement<AccomodationFindByOwnerRequest>(_AccomodationFindByOwnerRequest_QNAME, AccomodationFindByOwnerRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccomodationFindByOwnerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "accomodationFindByOwnerResponse")
    public JAXBElement<AccomodationFindByOwnerResponse> createAccomodationFindByOwnerResponse(AccomodationFindByOwnerResponse value) {
        return new JAXBElement<AccomodationFindByOwnerResponse>(_AccomodationFindByOwnerResponse_QNAME, AccomodationFindByOwnerResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentFindByAccOwnerRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentFindByAccOwnerRequest")
    public JAXBElement<ArrangmentFindByAccOwnerRequest> createArrangmentFindByAccOwnerRequest(ArrangmentFindByAccOwnerRequest value) {
        return new JAXBElement<ArrangmentFindByAccOwnerRequest>(_ArrangmentFindByAccOwnerRequest_QNAME, ArrangmentFindByAccOwnerRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrangmentFindByAccOwnerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "arrangmentFindByAccOwnerResponse")
    public JAXBElement<ArrangmentFindByAccOwnerResponse> createArrangmentFindByAccOwnerResponse(ArrangmentFindByAccOwnerResponse value) {
        return new JAXBElement<ArrangmentFindByAccOwnerResponse>(_ArrangmentFindByAccOwnerResponse_QNAME, ArrangmentFindByAccOwnerResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccomodationDeleteRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "accomodationDeleteRequest")
    public JAXBElement<AccomodationDeleteRequest> createAccomodationDeleteRequest(AccomodationDeleteRequest value) {
        return new JAXBElement<AccomodationDeleteRequest>(_AccomodationDeleteRequest_QNAME, AccomodationDeleteRequest.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingFindByIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "RatingFindByIdRequest")
    public JAXBElement<RatingFindByIdRequest> createRatingFindByIdRequest(RatingFindByIdRequest value) {
        return new JAXBElement<RatingFindByIdRequest>(_RatingFindByIdRequest_QNAME, RatingFindByIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingFindByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "RatingFindByIdResponse")
    public JAXBElement<RatingFindByIdResponse> createRatingFindByIdResponse(RatingFindByIdResponse value) {
        return new JAXBElement<RatingFindByIdResponse>(_RatingFindByIdResponse_QNAME, RatingFindByIdResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingSaveRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "ratingSaveRequest")
    public JAXBElement<RatingSaveRequest> createRatingSaveRequest(RatingSaveRequest value) {
        return new JAXBElement<RatingSaveRequest>(_RatingSaveRequest_QNAME, RatingSaveRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingSaveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "ratingSaveResponse")
    public JAXBElement<RatingSaveResponse> createRatingSaveResponse(RatingSaveResponse value) {
        return new JAXBElement<RatingSaveResponse>(_RatingSaveResponse_QNAME, RatingSaveResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriceSaveRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "priceSaveRequest")
    public JAXBElement<PriceSaveRequest> createPriceSaveRequest(PriceSaveRequest value) {
        return new JAXBElement<PriceSaveRequest>(_PriceSaveRequest_QNAME, PriceSaveRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriceSaveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "priceSaveResponse")
    public JAXBElement<PriceSaveResponse> createPriceSaveResponse(PriceSaveResponse value) {
        return new JAXBElement<PriceSaveResponse>(_PriceSaveResponse_QNAME, PriceSaveResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriceSheduleSaveRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "priceSheduleSaveRequest")
    public JAXBElement<PriceSheduleSaveRequest> createPriceSheduleSaveRequest(PriceSheduleSaveRequest value) {
        return new JAXBElement<PriceSheduleSaveRequest>(_PriceSheduleSaveRequest_QNAME, PriceSheduleSaveRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriceSheduleSaveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "priceSheduleSaveResponse")
    public JAXBElement<PriceSheduleSaveResponse> createPriceSheduleSaveResponse(PriceSheduleSaveResponse value) {
        return new JAXBElement<PriceSheduleSaveResponse>(_PriceSheduleSaveResponse_QNAME, PriceSheduleSaveResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "deleteResponse")
    public JAXBElement<DeleteResponse> createDeleteResponse(DeleteResponse value) {
        return new JAXBElement<DeleteResponse>(_DeleteResponse_QNAME, DeleteResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserFindByEmailAndPasswordRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "userFindByEmailAndPasswordRequest")
    public JAXBElement<UserFindByEmailAndPasswordRequest> createUserFindByEmailAndPasswordRequest(UserFindByEmailAndPasswordRequest value) {
        return new JAXBElement<UserFindByEmailAndPasswordRequest>(_UserFindByEmailAndPasswordRequest_QNAME, UserFindByEmailAndPasswordRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserFindByEmailAndPasswordResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "userFindByEmailAndPasswordResponse")
    public JAXBElement<UserFindByEmailAndPasswordResponse> createUserFindByEmailAndPasswordResponse(UserFindByEmailAndPasswordResponse value) {
        return new JAXBElement<UserFindByEmailAndPasswordResponse>(_UserFindByEmailAndPasswordResponse_QNAME, UserFindByEmailAndPasswordResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingFindByAccRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "ratingFindByAccRequest")
    public JAXBElement<RatingFindByAccRequest> createRatingFindByAccRequest(RatingFindByAccRequest value) {
        return new JAXBElement<RatingFindByAccRequest>(_RatingFindByAccRequest_QNAME, RatingFindByAccRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingFindByAccResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "ratingFindByAccResponse")
    public JAXBElement<RatingFindByAccResponse> createRatingFindByAccResponse(RatingFindByAccResponse value) {
        return new JAXBElement<RatingFindByAccResponse>(_RatingFindByAccResponse_QNAME, RatingFindByAccResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentFindByAccRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "commentFindByAccRequest")
    public JAXBElement<CommentFindByAccRequest> createCommentFindByAccRequest(CommentFindByAccRequest value) {
        return new JAXBElement<CommentFindByAccRequest>(_CommentFindByAccRequest_QNAME, CommentFindByAccRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentFindByAccResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "commentFindByAccResponse")
    public JAXBElement<CommentFindByAccResponse> createCommentFindByAccResponse(CommentFindByAccResponse value) {
        return new JAXBElement<CommentFindByAccResponse>(_CommentFindByAccResponse_QNAME, CommentFindByAccResponse.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageUpdateRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "messageUpdateRequest")
    public JAXBElement<MessageUpdateRequest> createMessageUpdateRequest(MessageUpdateRequest value) {
        return new JAXBElement<MessageUpdateRequest>(_MessageUpdateRequest_QNAME, MessageUpdateRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageUpdateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webService.projekat.xml/", name = "messageUpdateResponse")
    public JAXBElement<MessageUpdateResponse> createMessageUpdateResponse(MessageUpdateResponse value) {
        return new JAXBElement<MessageUpdateResponse>(_MessageUpdateResponse_QNAME, MessageUpdateResponse.class, null, value);
    }
}
